IMAGE_NAME = "bento/ubuntu-24.04"
PLAYBOOK = "provisioning/playbook.yaml"
N = 1

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
    end

    config.vm.define "k8s-master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "192.168.56.10"
        master.vm.hostname = "k8s-master"
        master.vm.network "forwarded_port", guest: 6443, host: 6443
    end

    (1..N).each do |i|
        config.vm.define "k8s-node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.56.#{i + 10}"
            node.vm.hostname = "k8s-node-#{i}"
        end
    end

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = PLAYBOOK
        ansible.groups = {
            "master" => ["k8s-master"],
            "node" => (1..N).map { |i| "k8s-node-#{i}" }
        }
    end
end
