# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.box_version = "1.0.282"
# Desconecta el puerto serie por https://www.virtualbox.org/ticket/18319
  config.vm.provider "virtualbox" do |vb|
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected"]
  end
  # 1
  # config.vm.provision :docker 
  # 2
  # config.vm.provision "docker" do |d|
  #   d.build_image '/vagrant/.', args: '-t hola-mundo'
  #   d.run 'hola-mundo'
  # end
  config.vm.provision "docker" do |d|
    d.run "hola-mundo", image: "dockersamples/static-site", args: "-p 8080:80"
  end
  config.vm.network "forwarded_port", guest: 8080, host: 8080
end
